@baseUrl=http://localhost:3000/api
@resourceName=todos
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJydW5vQGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiYnJ1bm8iLCJpYXQiOjE2NTE4Mzc3MjksImV4cCI6MTY1MTg0MTMyOX0.cI66qAN6oGO5vQBeufyRLvldaEE9aiHzvVJXIuN0T3E

# todos

# @name getAll
GET {{baseUrl}}/{{resourceName}}
Authorization: Bearer {{token}}

###

# @name filtertodos
GET {{baseUrl}}/{{resourceName}}?price_gte=900
Authorization: Bearer {{token}}

###

# @name filtertodos
GET {{baseUrl}}/{{resourceName}}?name_like=tasty


###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=20
Authorization: Bearer {{token}}


###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc


###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "id": "28759f7e-3509-4064-920a-406dd426033a",
  "title": "",
  "completed": true,
  "starred": true,
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/KkSXxPt
Content-Type: application/json

{
  "id": "28759f7e-3509-4064-920a-406dd426033a",
  "title": "",
  "completed": true,
  "starred": true,
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2




